name: Security pipeline — Docker + SBOM + Semgrep + Gitleaks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (juice-shop:latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: juice-shop:latest
          push: false
          load: true

      # 3️⃣ SBOM (Syft)
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (JSON)
        run: syft juice-shop:latest -o json > sbom.json

      - name: Generate SBOM (CycloneDX JSON) # opsiyonel
        run: syft juice-shop:latest -o cyclonedx-json > sbom.cdx.json || true

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            sbom.json
            sbom.cdx.json

      # 4️⃣ Semgrep SAST
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config p/ci --json --output semgrep-results.json .

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

      # 5️⃣ Gitleaks (secret scan)
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --report-path=gitleaks-report.json

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
