name: Security pipeline — docker build & SBOM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: juice-shop:latest
          push: false   # registry'ye push etmiyoruz
          load: true    # image runner içine yüklenir (Syft tarayabilsin diye)

      - name: Save image as artifact (opsiyonel)
        run: docker save juice-shop:latest -o juice-shop.tar

      - name: Upload docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: juice-shop-image
          path: juice-shop.tar

  sbom:
    name: Generate SBOM from Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: juice-shop-image
          path: .

      - name: Load docker image
        run: docker load -i juice-shop.tar

      - name: Install Syft (Anchore)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (JSON)
        run: |
          syft juice-shop:latest -o json > sbom.json
          echo "SBOM üretildi: sbom.json"

      - name: Generate SBOM (CycloneDX JSON)  # opsiyonel
        run: syft juice-shop:latest -o cyclonedx-json > sbom.cdx.json || true

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: |
            sbom.json
            sbom.cdx.json
